=== thetimeofblack/XMLpractice/ex1_document_type_definition/AviationDatabase.dtd
<!ELEMENT AviationDatabase (Airports, Airlines, Employees)>
<!ELEMENT Airports (Airport+)>
<!ELEMENT Airlines (Airline+)>
<!ELEMENT Employees (Employee+)>
<!ELEMENT Airport EMPTY>
<!ELEMENT Airline (Flight+)>
<!ELEMENT Flight EMPTY>
<!ELEMENT Employee ((FlightCrewMember | GroundCrewMember), Contract?)>
<!ELEMENT FlightCrewMember (flyingHours)>
<!ELEMENT GroundCrewMember (phone)>
<!ELEMENT flyingHours (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT Contract EMPTY>
<!ATTLIST Airport token ID #REQUIRED
                            city CDATA #REQUIRED
                            country CDATA #REQUIRED>
<!ATTLIST Airline token ID #REQUIRED
                            name CDATA #REQUIRED
                            homebase IDREF #REQUIRED>
<!ATTLIST Flight flightNo ID #REQUIRED
                           from IDREF #REQUIRED
                           to IDREF #REQUIRED>
<!ATTLIST Employee ssn ID #REQUIRED
                                  firstName CDATA #REQUIRED
                                  lastName CDATA #REQUIRED>
<!ATTLIST Contract dateOfSigning CDATA #REQUIRED
                               fixedTerm (true | false) "true"
                               airlineToken IDREF #REQUIRED>

=== thetimeofblack/XMLpractice/ex1_document_type_definition/airport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE AviationDatabase SYSTEM "AviationDatabase.dtd">

<AviationDatabase>
            <Airports>
                 <Airport token="Shanghai"  city="Shanghai" country = "China"></Airport> 
                 <Airport token="Germany"  city="Hamburg"  country="Germany"></Airport>
            </Airports>
            
            <Airlines>
                  <Airline token= "GermanyToShanghai" name="PuDong airport"  homebase="Germany">
                   <Flight flightNo="ETS" from="Germany" to="Shanghai"></Flight>                  
                  </Airline> 
                  
                  <Airline token="ShanghaiToGermany" name="Hamburg airport" homebase="Shanghai">               
                   <Flight flightNo="ENS" from="Shanghai" to="Germany"></Flight>                  
                  </Airline>            
            </Airlines>
            
            <Employees>
                  <Employee ssn="abcdefg" firstName="Yining" lastName="He">
                                 <FlightCrewMember>
                                         <flyingHours>10</flyingHours>
                                 </FlightCrewMember>
                                 <Contract dateOfSigning="11/11/2018" fixedTerm="false" airlineToken="ShanghaiToGermany"></Contract>
                  </Employee>  
                  
                  <Employee ssn="master" firstName="XiaoFang" lastName="He">
                                  <GroundCrewMember>
                                          <phone>1147823723</phone>
                                  </GroundCrewMember>
                                  <Contract dateOfSigning="20/09/2018" fixedTerm="true" airlineToken="GermanyToShanghai"></Contract>
                  </Employee>
                  
            </Employees>
</AviationDatabase>
