=== thetimeofblack/XMLpractice/ex2_xpath/zoo.dtd
<!ELEMENT zoo (animal+)>
<!ELEMENT animal ((corral | aquarium), keeper+)>
<!ELEMENT corral (location)>
<!ELEMENT aquarium (location)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT keeper (#PCDATA)>
<!ATTLIST keeper dayOff (Mo|Tu|We|Th|Fr|Sa|Su) "Su">
<!ATTLIST animal species CDATA #REQUIRED
                            weight CDATA #IMPLIED>

=== thetimeofblack/XMLpractice/ex1_document_type_definition/zoo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zoo SYSTEM "zoo.dtd">
<zoo>
	<animal species="elephant" weight="500">
		<corral>
			<location>entrance</location>
		</corral>
		<keeper>Sally Sunshine</keeper>
		<keeper dayOff="Fr">Susan Sandbox</keeper>
	</animal>
		<animal species="giraffe" weight="250">
		<corral>
			<location>central park</location>
		</corral>
		<keeper>Sarah Strange</keeper>
	</animal>
		<animal species="dolphin" weight="80">
		<aquarium>
			<location>Aquahouse</location>
		</aquarium>
	<keeper dayOff="Mo">Steve Sportsman</keeper>
	</animal>
</zoo>
